name: pa11y tests

on: [pull_request]

jobs:
  build:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install jekyll site dependencies.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install pa11y-ci dependencies.
        run: npm install

      - name: Start up jekyll server.
        run: npm run start-detached

      - name: Run pa11y-ci.
        id: pa11y_test_results
        run: echo "::set-output name=pa11y-ci-output::$(npm run pa11y-ci:home)"
        
      - name: Comment on pull request
        uses: thollander/actions-comment-pull-request@1.0.0
        with:
          message: '${{ steps.pa11y_test_results.outputs.pa11y_test_results }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
