name: QA pull request

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    name: Building QA site to review pull request
    if: contains(github.event.pull_request.labels.*.name, 'qa-pull-request')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2
        
      - name: Find and replace the main site domain
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "accessibility.civicactions.com"
          replace: "accessibility-qa.dmundra.dev"
          
      - name: Replace contents of robots.txt
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Sitemap: https://accessibility-qa.dmundra.dev/sitemap.xml"
          replace: |
            User-agent: *
            Disallow: /
          include: "robots.txt"
        
      - name: Install jekyll site dependencies.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          
      - name: Build jekyll site.
        run: bundle exec jekyll build
        
      - name: Push _site directory to QA repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '_site'
          destination-github-username: 'dmundra'
          destination-repository-name: 'accessibility-qa'
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
          
      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "You can test changes in this branch at [https://accessibility-qa.dmundra.dev/](https://accessibility-qa.dmundra.dev/). If you pushed additional changes, remove and readd the label 'qa-pull-request'."
