name: QA pull request

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    name: Building QA site to review pull request
    if: contains(github.event.pull_request.labels.*.name, 'qa-pull-request')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2
        
      - name: Push branch to QA repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'dmundra'
          destination-repository-name: 'accessibility-qa'
          target-branch: main
          
      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: 'QA changes at [https://dmundra.github.io/accessibility-qa/](https://dmundra.github.io/accessibility-qa/).'
