name: QA pull request

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    name: Building QA site to review pull request
    if: ${{ github.event.label.name == 'qa-pull-request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2
