name: QA pull request

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    name: Building QA site to review pull request
    if: contains(github.event.pull_request.labels.*.name, 'qa-pull-request')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2
        
      - name: Find and replace CNAME
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "accessibility.civicactions.com"
          replace: "accessibility-qa.dmundra.dev"
          include: "CNAME"
        
      - name: Install jekyll site dependencies.
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          
      - name: Build jekyll site.
        run: bundle exec jekyll build
        
      - name: Push site directory to QA repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '_site'
          destination-github-username: 'dmundra'
          destination-repository-name: 'accessibility-qa'
          user-email: daniel.mundra@civicactions.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
          
      - name: Comment on pull request.
        uses: thollander/actions-comment-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: 'QA changes at [https://dmundra.github.io/accessibility-qa/](https://dmundra.github.io/accessibility-qa/).'
